"""add question_types to quizzes

Revision ID: 16071d93d095
Revises: e71b2d605970
Create Date: 2026-07-11 06:44:00.622798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '16071d93d095'
down_revision: Union[str, None] = 'e71b2d605970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'question_types')
    # ### end Alembic commands ###
